//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 使用者 mfc_demo.rc

#define IDS_APP_TITLE			103

#define IDR_MAINFRAME			128
#define IDD_MFCDEMO_DIALOG	102
#define IDD_ABOUTBOX			103
#define IDM_ABOUT				104
#define IDM_EXIT				105
#define IDM_DIRECTORY_OPEN		32771
#define IDM_PLAY				32772
#define IDM_PAUSE				32773
#define IDM_STOP				32774
#define IDM_VOLUME				32775
#define IDD_VOLUME_DIALOG		112
#define IDC_VOLUME_SLIDER		1001
#define IDC_VOLUME_STATIC		1002
#define IDS_HINT_OPEN_FILE		201
#define IDS_STATUS_PLAYING		202
#define IDS_STATUS_PAUSED		203
#define IDS_STATUS_LOADED		204
#define IDS_ERR_OPEN_MP3		205
#define IDS_ERR_PLAY			206
#define IDS_HINT_NO_FILE		207
#define IDS_VOLUME_TITLE		208
#define IDS_VOLUME_LABEL		209
#define IDI_MFCDEMO			107
#define IDI_SMALL				108
#define IDC_MFCDEMO			109
#define IDC_MYICON				2
#ifndef IDC_STATIC
#define IDC_STATIC				-1
#endif
// 新对象的下一组默认值
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NO_MFC					130
#define _APS_NEXT_RESOURCE_VALUE	129
#define _APS_NEXT_COMMAND_VALUE		32771
#define _APS_NEXT_CONTROL_VALUE		1000
#define _APS_NEXT_SYMED_VALUE		110
#endif
#endif
